name: Test great_expectation

on: pull_request


jobs:
  sqlfluff-lint-models:
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    environment:
      name: env
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.8]

    steps:
      - name: Checkout PR by removing the merge into main
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install great_expectation
        run: |
          python -m pip install --upgrade pip
          pip install great_expectations
          pip install sqlalchemy
          pip install psycopg2-binary

      - name: run great_expectation checkpoint
        run: |
          great_expectations checkpoint run myfirstCheckpoint

