name: Test a complete CICD process

on: push

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR by removing the merge into main
        id: Checkout-code
        uses: actions/checkout@v2
      - name: Install dependencies
        id: Install-dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
