name: Test a complete CICD process

on: push

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR by removing the merge into main
        id: Checkout-code
        uses: actions/checkout@v2
      - name: Install dependencies
        id: Install-dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip

          pip install sqlfluff==0.9.1
          pip install sqlfluff-templater-dbt==0.9.1

          pip install great_expectations
          pip install sqlalchemy
          pip install psycopg2-binary

          pip install prefect[gitlab,dateutil,dask,distributed,great-expectations,pandas]

          pip install dbt-postgres
          pip install pygit2
          dbt deps
