name: Test a complete CICD process

on: push

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR by removing the merge into main
        id: Checkout-code
        uses: actions/checkout@v2

  check-model-modified-to-lint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        id: Install-dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff==0.9.1
          pip install sqlfluff-templater-dbt==0.9.1

      - name: Get changed files
        if: ${{ success() }}
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '

      - name: Get changed .sql files in /models to lint
        id: get_files_to_lint
        run: |
          # Set the command in the $() brackets as an output to use in later steps
          echo "::set-output name=lintees::$(
          # Issue where grep regular expressions don't work as expected on the
          # Github Actions shell, check models/ and analysis/ folders seperately
          echo \
          $(echo ${{ steps.get_file_changes.outputs.files }} |
          tr -s ' ' '\n' |
          grep -E '^models.*[.]sql$' |
          tr -s '\n' ' ') \
          )"

      - name: Lint dbt models
        id: lint
        shell: bash -l {0}
        if: steps.get_files_to_lint.outputs.lintees != ''
        run: |
          sqlfluff lint ${{ steps.get_files_to_lint.outputs.lintees }}

  prefect-dbt-elt:
    needs: prefect invoke dbt task to perform etl
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        id: Install-dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install prefect[gitlab,dateutil,dask,distributed,great-expectations,pandas]
          pip install dbt-postgres
          pip install pygit2
          dbt deps

      - name: login prefect cloud
        if: ${{ success() }}
        run: |
          prefect backend cloud
          prefect auth login --key pcu_BALmdcZHkFBm0Hyw3s1EjbE7YFpNmJ0qYQ5N

      - name: start agent backend
        run: |
          nohup prefect agent local start -l myAgentLable > agent.log 2>&1 &

      - name: register flow
        run: |
          pwd
          ls
          prefect register --project dbt_tutorial -p ./flows/dbtTest.py -n "dbtTest" -l "myAgentLable"

      - name: run prefect with dbt
        run: |
          prefect run -n "dbtTest" --label "myAgentLable"

      - name: Wait for the process to finish
        run: sleep 180s
        shell: bash

  Check-data-quality-by-great-expectation:
    needs: Check data quality with expectation
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        id: Install-dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install great_expectations
          pip install sqlalchemy
          pip install psycopg2-binary

      - name: run great_expectation checkpoint
        if: ${{ success() }}
        run: |
          great_expectations checkpoint run myfirstCheckpoint
